### ISSUE TITLE
FileNotFoundException for apache-maven-3.2.5-bin.zip

### ISSUE THREAD

**Issue by jsotogaviard** [rimerosolutions/maven-wrapper-example#7]
Hi

When I git clone the project and run mvnw.bat clean I get the error (1).
When I look into the folder .m2 I get the image in (2)

Any input ?

Jonathan
(1)c:\\workspace_\maven-wrapper-example>mvnw.bat install
janv. 10, 2017 1:50:59 PM org.apache.maven.wrapper.Installer createDistFromUri
INFOS: Downloading https://repository.apache.org/content/repositories/releases/org/apache/maven/apache-maven/3.2.5/apache-maven-3.2.5-bin.zip
.....................................................................................................................................................................................................................................................................
..............................................................................................................................................
janv. 10, 2017 1:51:04 PM org.apache.maven.wrapper.Installer verifyDistribution
INFOS: Verifying download with https://repository.apache.org/content/repositories/releases/org/apache/maven/apache-maven/3.2.5/apache-maven-3.2.5-bin.zip.md5

janv. 10, 2017 1:51:05 PM org.apache.maven.wrapper.Installer createDistFromUri
INFOS: Unzipping C:\Users\JonathanSotto\.m2\wrapper\dists\apache-maven-3.2.5-bin\2uov6ia0vgqdlaiml7ae5qkoh\apache-maven-3.2.5-bin.zip to C:\Users\JonathanSotto\.m2\wrapper\dists\apache-maven-3.2.5-bin\2uov6ia0vgqdlaiml7ae5qkoh
janv. 10, 2017 1:51:05 PM org.apache.maven.wrapper.Installer createDist
AVERTISSEMENT: Maven distribution 'https://repository.apache.org/content/repositories/releases/org/apache/maven/apache-maven/3.2.5/apache-maven-3.2.5-bin.zip' failed: C:\Users\JonathanSotto\.m2\wrapper\dists\apache-maven-3.2.5-bin\2uov6ia0vgqdlaiml7ae5qkoh\apac
he-maven-3.2.5-bin.zip (Le fichier spÚcifiÚ est introuvable)
Exception in thread "main" java.io.FileNotFoundException: C:\Users\JonathanSotto\.m2\wrapper\dists\apache-maven-3.2.5-bin\2uov6ia0vgqdlaiml7ae5qkoh\apache-maven-3.2.5-bin.zip (Le fichier spécifié est introuvable)
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.zip.ZipFile.<init>(ZipFile.java:163)
        at org.apache.maven.wrapper.Installer.unzip(Installer.java:270)
        at org.apache.maven.wrapper.Installer.createDistFromUri(Installer.java:113)
        at org.apache.maven.wrapper.Installer.createDist(Installer.java:63)
        at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:136)
        at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:56)

(2)
![image](https://cloud.githubusercontent.com/assets/3329978/21806887/397bed98-d73c-11e6-85e8-42b1e701c1dd.png)

**Comment by jsotogaviard** [comment]
It is probably related to the fact that I am using java8.
I have recompiled the project and created a new jar. Everything works as expected
